Feature/ab#1210 create testdata
starwit/ai-cockpit pull request #56
Opened 2024-09-04 08:42 UTC by flostyl3

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-04 13:59 UTC, witchpou requested changes
Bitte einfach nochmal testen, ob der Testdatenimport noch funktioniert.

2024-09-04 13:59 UTC, witchpou commented on webclient/app/src/app/features/trafficIncident/TrafficIncidentOverview.jsx
> +    const [trafficIncidents0, setTrafficIncidents0] = useState([]);
kannst du das vielleicht newIncidents und checkedIncidents nennen? Oder so ähnlich.

2024-09-04 13:59 UTC, witchpou commented on persistence/src/main/resources/db/migration/V2_0__fill.sql
> -INSERT INTO "trafficincidenttype" ("name")
Ich habe hier die alten Typen rausgenommen. Kannst du bitte mal schauen, ob der Import noch funktioniert?

2024-09-04 14:54 UTC, flostyl3 commented
> Kannst du bitte auch die default Maßnahmen mit im Testscript setzen. Die Lösung mit dem Shell-Script gefällt mir :-).

Was meinst du mit default Maßnahmen?

2024-09-11 09:35 UTC, witchpou approved these changes

2024-09-11 10:10 UTC, merged